name: Publish package to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write    
    steps:
      # Checkout of the repository
      - name: Checkout
        uses: actions/checkout@v3
      # Usage of Java Development Kit
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:       
          java-version: '17'
          distribution: 'adopt'
          server-id: github
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      # Compile the Java project
      - name: Build with Maven
        run: mvn -B -Pgithub package --file pom.xml
        env:
          MAVEN_USERNAME: ${{ secrets.ULLSOFTWARE_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.ULLSOFTWARE_PASSWORD }}
      # Publish the artifact to GitHub Packages          
      - name: Publish package
        run: mvn -Pgithub deploy --file pom.xml
        env:
          MAVEN_USERNAME: ${{ github.actor }}
          MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
